apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-deployment
  labels:
    app: {{ .Values.prefix }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.prefix }}
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}
    spec:
      containers:
      - name: {{ .Values.prefix }}
        image: '{{ .Values.image.name }}:{{ .Values.appVersion }}'
        ports:
        - containerPort: {{ .Values.configMap.PORT }}
