apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.prefix }}
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}
    spec:
      containers:
      - name: {{ .Values.prefix }}
        image: '{{ .Values.image.name }}:{{ .Values.appVersion }}'
        ports:
        - containerPort: {{ .Values.configMap.PORT }}
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.prefix }}-config
              key: PORT
        - name: REACT_APP_API_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.prefix }}-config
              key: REACT_APP_API_HOST
