apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-service
spec:
  selector:
    app: {{ .Values.prefix }}
  ports:
  - protocol: TCP
    port: {{ .Values.configMap.PORT }}  # External port for accessing your application
    targetPort: {{ .Values.configMap.PORT }}  # Port exposed by your Node.js container 
  type: {{ .Values.service.type }}
