apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-service
  labels:
    app: vdt
spec:
  selector:
    app: {{ .Values.prefix }}
  ports:
  - name: port
    protocol: TCP
    port: {{ .Values.configMap.PORT }}  # External port for accessing your application
    targetPort: {{ .Values.configMap.PORT }}  # Port exposed by your Node.js container 
  type: {{ .Values.service.type }}
